"""Ask Claude about a case you just answered: an optional tutor in the follow-up block of the debrief.

Needs the ``anthropic`` package (``pip install -e ".[tutor]"``), an internet connection and Anthropic credentials
(``ANTHROPIC_API_KEY``, an ``ant auth login`` profile, or a key typed on the page and kept only for that browser
session). Every question costs API usage. What is sent: the case (synthetic practice data), your answers, your
message, the comments on your wrong answers and the conversation so far. Questions that look like they contain
company-confidential material are not sent.
"""

from __future__ import annotations

import re
from collections.abc import Iterator

from . import Case, message_checklist, role_name

MODEL = "claude-opus-5-5"
FALLBACK_BETA = "server-side-fallback-2026-07-01"  # fallbacks="default": a declined question is retried server-side
# words that suggest real company material; such questions are kept on this PC
BLOCKED = re.compile(r"micron|美光|confidential|機密|機敏|proprietary|internal use only|僅限內部", re.I)

INSTRUCTIONS = """You are a patient, precise tutor for a metrology applications engineer (Metro AE) practising \
semiconductor-fab case studies in a training dashboard. All case data is synthetic practice data generated by the \
tool; lot IDs, tools and numbers are made up.

The learner has just answered the case below. Your job is to clear up their misunderstandings:
- Answer the question they ask. Explain why their choice does or does not fit, using this case's own numbers and \
the chart that decides it (name the chart). Contrast the evidence their choice would need with what the data shows.
- When it helps, end with one short check question they can answer to confirm they now see it.
- Use generic fab practice (OCAP: verify the measurement first, contain, notify, fix, qual). Say so when an answer \
depends on a specific fab's rules instead of inventing a policy.
- Reply in the learner's language: {lang_rule}
- Be concise: short paragraphs or a few bullets; no preamble.
- Never ask for and never repeat real company data, real lot IDs, product names, recipe names or people's names. If \
the learner offers such details, remind them briefly to keep real work data out of this tool and answer in generic \
terms."""

LANG_RULE = {"zh": "Traditional Chinese (Taiwan fab usage; keep English technical terms where engineers use them).",
             "en": "English.",
             "both": "Traditional Chinese first, then the same answer in English."}


def available() -> bool:
    try:
        import anthropic  # noqa: F401
    except ImportError:
        return False
    return True


def guard(text: str) -> str | None:
    """A reason not to send this question, or None."""
    if not (text or "").strip():
        return "請先輸入問題。 Type a question first."
    if BLOCKED.search(text):
        return ("這個問題看起來包含公司機密或公司名稱，所以沒有送出。請改用一般性的描述（不要放真實 lot、產品、recipe 或人名）。"
                " This question looks like it contains company-confidential material or a company name, so it was not sent. "
                "Rephrase it in generic terms (no real lots, products, recipes or names).")
    return None


def case_context(case: Case, answers: dict, result: dict, lang: str = "en") -> str:
    """Everything the tutor needs about this attempt, as plain text."""
    from . import why

    lg = "zh" if lang == "zh" else "en"
    out = [f"CASE {case.id} ({case.level}): {case.text('title', lg)}", "", "SITUATION", case.text("brief", lg), "",
           "WHAT THE CHARTS SHOW (findings computed from the data)"]
    for key, f in case.guide:
        out.append(f"- [{key}, status {f.status}] " + " ".join(f.zh if lg == "zh" else f.en))
    out += ["", "QUESTIONS, THE LEARNER'S ANSWERS AND THE MODEL ANSWERS"]
    for q in case.questions:
        r = result["questions"][q.key]
        head = q.label[lg] + (f" ({q.group[lg]})" if q.group else "")
        if q.kind == "single":
            opts = "; ".join(q.option_text(o, lg) for o in q.options)
            mine = q.option_text(r["answer"], lg) if r["answer"] else "(no answer)"
            out.append(f"- {head}: options [{opts}] | learner: {mine} | model: {q.option_text(r['correct'], lg)} | "
                       f"{'RIGHT' if r['ok'] else 'WRONG'}")
        else:
            name = (lambda o: role_name(o, lg) if q.kind == "roles" else q.option_text(o, lg))  # noqa: E731
            out.append(f"- {head}: learner: {', '.join(map(name, r['answer'])) or '(none)'} | model: "
                       f"{', '.join(map(name, r['correct'])) or '(none)'} | {'RIGHT' if r['ok'] else 'PARTLY WRONG'}")
    out += [f"Score: {result['total']:.0f} / 100", "", "WHY (the model explanation)", case.text("explanation", lg), "",
            "THE LEARNER'S MESSAGE", answers.get("message") or "(empty)", "", "MODEL MESSAGE", case.text("model_message", lg),
            "", "MESSAGE CHECKLIST"]
    out += [f"- {'covered' if ok else 'missing'}: {item}" for item, ok in message_checklist(case, answers.get("message", ""), lg)]
    items = why.comments(case, result)
    if items:
        out += ["", "COMMENTS ALREADY SHOWN ON THE WRONG ANSWERS"]
        for c in items:
            out += [f"* {c['q'].label[lg]}"] + [f"  {ln}" for ln in why.comment_lines(case, c, lg)]
    return "\n".join(out)


def system_prompt(case: Case, answers: dict, result: dict, lang: str = "both") -> str:
    return (INSTRUCTIONS.format(lang_rule=LANG_RULE.get(lang, LANG_RULE["both"])) + "\n\n<case>\n"
            + case_context(case, answers, result, "zh" if lang == "zh" else "en") + "\n</case>")


def make_client(api_key: str | None = None):
    import anthropic

    return anthropic.Anthropic(api_key=api_key) if api_key else anthropic.Anthropic()


def ask(system: str, history: list[dict], api_key: str | None = None, client=None) -> Iterator[str]:
    """Stream the tutor's answer to the last user turn of ``history`` ([{role, content}], append-only). Yields text;
    errors and declines come back as a readable line instead of an exception."""
    import anthropic

    try:
        client = client or make_client(api_key)
        with client.beta.messages.stream(
            model=MODEL,
            max_tokens=16000,
            system=[{"type": "text", "text": system, "cache_control": {"type": "ephemeral"}}],
            messages=history,
            output_config={"effort": "medium"},
            betas=[FALLBACK_BETA],
            fallbacks="default",
        ) as stream:
            yield from stream.text_stream
            final = stream.get_final_message()
        if final.stop_reason == "refusal":
            yield ("\n\n（這個問題沒有得到回答，請換個方式問。） (This question was declined; try asking it another way.)")
        elif final.stop_reason == "max_tokens":
            yield "\n\n（回答太長被截斷。） (The answer was cut off.)"
    except (anthropic.AuthenticationError, TypeError):  # TypeError: no credentials at all, the client cannot be built
        yield ("找不到有效的 Anthropic 金鑰：請設定 ANTHROPIC_API_KEY、執行 `ant auth login`，或在上方輸入金鑰。 "
               "No valid Anthropic credentials: set ANTHROPIC_API_KEY, run `ant auth login`, or enter a key above.")
    except anthropic.RateLimitError:
        yield "目前請求太多，請稍後再問。 Too many requests right now; try again in a minute."
    except anthropic.APIConnectionError:
        yield "連不上 Anthropic（沒有網路或被防火牆擋住）。 Cannot reach Anthropic (no internet, or a firewall blocks it)."
    except anthropic.APIStatusError as e:
        yield f"Anthropic API 錯誤 error {e.status_code}: {e.message}"


__all__ = ["MODEL", "ask", "available", "case_context", "guard", "make_client", "system_prompt"]
